site_name: Documentação IdeiaSpace

repo_url: https://github.com/mdsreq-fga-unb/2024.2-T01-IdeaSpace
repo_name: IdeiaSpace

nav:
  - Home: "index.md"
  - Visão de Produto e Projetos:
      - Cenário atual do cliente e do negócio: produto/visao-produto-projeto.md
      - Solução proposta: produto/solucao.md
      - Estratégias de Engenharia de Software: produto/estrategias.md
      - Cronograma e entregas: produto/cronograma-entregas.md
      - Interação entre equipe e cliente: produto/interacao.md
  - Engenharia de Requisitos:
    - Atividades e Técnicas de ER: engenharia-requisitos/atividades_er.md
    - Backlog: engenharia-requisitos/backlog.md
  - Apresentações: apresentacoes/index.md
  - Lições aprendidas: 
    - Unidade 1: licoes/unidade1.md
    - Unidade 2: licoes/unidade2.md

theme:
  name: material
  favicon: assets/ideaspace_icon.png
  logo: assets/ideaspace_icon.png

  palette:
    - scheme: default
      primary: "indigo"
      accent: "pink"
      toggle:
        icon: material/lightbulb
        name: Dark mode

    - scheme: slate
      primary: "indigo"
      accent: "pink"
      toggle:
        icon: material/lightbulb-outline
        name: Light mode
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    - search
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top

extra_css:
  - stylesheets/style.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-video
  - glightbox
